name: Mail Kagoya
on: [push]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      # TOをmail_to.txから読込む
      - name: Read mail addresses from separate files
        run: |
          TO_VAL=$(cat mail_to.txt | tr '\r\n' ',' | sed 's/,$//' | tr -d '\r\n')
          echo "TO=$TO_VAL" >> $GITHUB_ENV

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.atlantis21.co.jp
          server_port: 587
          username: ${{ secrets.MAIL_KAGOYA_USER }}
          password: ${{ secrets.MAIL_KAGOYA_PW }}
          ignore_cert: true
          subject: "GitHub Commit - ${{ github.repository }}"
          to: ${{ env.TO }}
          from: '"GitHubCommit" <svn@atlantis21.co.jp>'
          body: |
            Author: ${{ github.actor }}
            Date: ${{ github.event.head_commit.timestamp }}
            New Revision: ${{ env.SHORT_SHA }}
            
            Log: 
            ${{ github.event.head_commit.message }}
            
            URL: ${{ github.event.compare }}